### ISSUE TITLE
Error xpath on Odoo v9

### ISSUE THREAD

**Issue by kkoci** [treytux/odoo-website#2]
Hi/Hola

Estaba tratando de instalar algunos de sus módulos en la versión 9 de Odoo

Pero tengo éste error:

Full Traceback:

Odoo Server Error
Traceback (most recent call last):
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/http.py", line 599, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/http.py", line 636, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/http.py", line 315, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/http.py", line 308, in checked_call
    result = self.endpoint(_a, *_kw)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/http.py", line 887, in __call__
    return self.method(_args, *_kw)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/http.py", line 465, in response_wrap
    response = f(_args, *_kw)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/addons/web/controllers/main.py", line 975, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/python/apps/odoo/instances/sukotto/odoo/addons/web/controllers/main.py", line 963, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/api.py", line 232, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/api.py", line 232, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/addons/base/module/module.py", line 533, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/modules/registry.py", line 385, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/modules/loading.py", line 337, in load_modules
    loaded_modules, update_module)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/tools/convert.py", line 852, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/tools/convert.py", line 939, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/tools/convert.py", line 802, in parse
    self.parse(rec, mode)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/tools/convert.py", line 805, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/tools/convert.py", line 709, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/api.py", line 232, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/addons/base/ir/ir_model.py", line 1107, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/api.py", line 232, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/addons/base/ir/ir_ui_view.py", line 351, in create
    context=context)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/api.py", line 232, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/api.py", line 327, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/models.py", line 4125, in create
    record = self.browse(self._create(old_vals))
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/api.py", line 230, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/api.py", line 463, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/models.py", line 4316, in _create
    recs._validate_fields(vals)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/api.py", line 230, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/python/apps/odoo/instances/sukotto/odoo/openerp/models.py", line 1267, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "Invalid view definition

Error details:
View inheritance may not use attribute 'string' as a selector.

Error context:
View `Website settings`
[view_id: 997, xml_id: n/a, model: website.config.settings
None" while parsing 

/opt/python/apps/odoo/instances/sukotto/odoo/addons/website_sale_products_per_page/views/res_config.xml:5, near

'''<record id=   "view_website_config_settings"                 model="ir.ui.view">
            <field name=  "name"   >    Website settings      </field>
            <field name=   "model"  >website.config.settings</field>
            <field name=   "inherit_id" ref="website.view_website_config_settings"/>
            <field name="   arch   " type="xml">
                <data>
                    <xpath expr="//group[@string='Menu']" position="after">
                        <group string="Shop">
                            <label for="shop_products_per_page"/>
                            <div name="shop_products_per_page">
                                <div>
                                    <div name="shop_products_per_page" class="oe_inline">
                                        <field name="shop_products_per_page"/>
                                    </div>
                                </div>
                            </div>
                        </group>
                    </xpath>
                </data>
            </field>
        </record>'''

Sé que fueron hechos para la versión 8, y ésto del xpath/nombre como 'string' ya está deprecado, lo que quería saber es si es algo sencillo de resolver y si sabes como?

De antemano Gracias!

EDIT

No me deja colocar toda la vista xml, el error está en ésta línea:

xpath expr="//group[@string='Menu']" position="after"

**Comment by jctrey** [comment]
Hola Kristian,

Los módulos actualmente publicados en la rama odoo-website solo son para 
la v8. Por el momento ninguno de ellos se ha portado a la v9.

Gracias en cualquier caso por tu comentario.

Un saludo, jorge.

**Comment by kkoci** [comment]
Gracias Jorge, creo que ésto se puede resolver rápido

Trataré de resolverlo por mi lado, Gracias de nuevo!
